import Head from "next/head";
import { BsSkype, BsSlack, BsDiscord } from "react-icons/bs";
import { FaDiscord } from "react-icons/fa";
export default function Home() {
  return (
    <div>
      <Head>
        <title>Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="bg-white px-10">
        <section className="min-h-screen">
          <nav className="py-10 mb-12 flex justify-between">
            <h1 className="text-2xl font-burtons">Portfolio</h1>
            <ul className="flex items-center gap-5">
              <li>
                <a
                  href="#about"
                  className="text-xl capitalize text-black font-burtons"
                >
                  about us
                </a>
              </li>
              <li>
                <a
                  href="#service"
                  className="text-xl capitalize text-black font-burtons"
                >
                  service
                </a>
              </li>
              <li>
                <a
                  href="#work"
                  className="text-xl capitalize text-black font-burtons"
                >
                  Work
                </a>
              </li>

              <li>
                <a
                  href="https://discord.com/invite/XtNAqS8Adv"
                  target="_blank"
                  rel="noreferrer"
                  className="bg-gradient-to-r from-red-500 to-red-500 text-white px-4 py-2 border-none rounded-md ml-8 flex items-center gap-2"
                >
                  <FaDiscord className="cursor-pointer" />
                  Join Discord
                </a>
              </li>
            </ul>
          </nav>
          <div className="text-center md:text-left p-10" id="about">
            <h2 className="text-5xl py-2 text-teal-600 font-medium">
              ZhangZhiXin
            </h2>
            <h3 className="text-2xl py-2">
              Web Developer | Mobile app Developer | Desktop App Developer
            </h3>
            <p className="text-md py-5 leading-8 text-gray-800 max-w-screen-xl">
              I am a Full Stack Developer who has more than 6 years of
              experience on the web and mobile app development. As experience, I
              worked on freelancer(3 years), upwork(2 years) and discord(2
              years). During that time I got the large experience on the
              frontend and backend development. as well as I will give you
              perfect and awesome result and credit is very important for me on
              that.
            </p>
            <div className="flex flex-col">
              <h1 className="font-bold text-2xl mb-4">Technologies</h1>
              <ul className="flex flex-col gap-3">
                <li className="text-xl font-500">React.js/Next.js</li>
                <li className="text-xl font-500">Vue.js/Nuxt.js</li>
                <li className="text-xl font-500">Angular/Angular.js</li>
                <li className="text-xl font-500">Node/Express.js</li>
                <li className="text-xl font-500">PHP/Laravel/CI</li>
                <li className="text-xl font-500">React Native cli/Expo</li>
                <li className="text-xl font-500">Javascript/Typescript</li>
                <li className="text-xl font-500">Electron.js</li>
                <li className="text-xl font-500">Python/Django</li>
                <li className="text-xl font-500">SQL,MySQL,MongoDB etc</li>
                <li className="text-xl font-500">
                  Tailwind CSS, SCSS,Bootstrap, Material
                </li>
              </ul>
            </div>
          </div>
          <div id="service"></div>
          <div id="work"></div>

          <a className="flex items-center rounded-md justify-center gap-16 py-2">
            <BsSkype className="cursor-pointer" />
            <BsSlack className="cursor-pointer" />
            <BsDiscord className="cursor-pointer" />
          </a>
        </section>
      </main>
    </div>
  );
}
