import Head from 'next/head'
export default function Home() {
  return (
    <div>
      <Head>
        <title>Example Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
       
      </main>

     
    </div>
  )
}
